import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import type { ReportItem } from "@/services/room-client";

const players = [
  ["林舟", "已准备", "#213C38"],
  ["Mia", "已准备", "#765B4D"],
  ["Alex", "检查麦克风", "#584A37"],
  ["苏晴", "连接中", "#3B4C55"],
];

function Header({ title, back }: { title: string; back?: () => void }) {
  return <View style={styles.header}>{back ? <Pressable accessibilityLabel="离开房间" onPress={back}><Text style={styles.back}>‹</Text></Pressable> : <View style={styles.logo}><Text style={styles.book}>▰</Text><Text style={styles.logoText}>English Room</Text></View>}<View style={styles.profile}><Text>●</Text></View></View>;
}

function BottomTabs() { return <View style={styles.tabs} testID="lobby-bottom-tabs"><Text style={styles.tabActive}>⌂{"\n"}大厅</Text><Text style={styles.tab}>▣{"\n"}房间</Text><Text style={styles.tab}>♙{"\n"}我的</Text></View>; }

export function LobbyScreen({ onCreate, onJoin }: { onCreate: () => void; onJoin: () => void }) {
  const [code, setCode] = useState("");
  return <SafeAreaView style={styles.safe}><View style={styles.lobby}><Header title="" /><Text style={styles.lobbyTitle}>用英语进入今晚的故事</Text><Text style={styles.lobbyPrompt}>今晚想练哪一句？</Text><View style={styles.smallRule}><View /><Text>✦</Text><View /></View>
    <View style={styles.portCard}><View style={styles.portMist} /><Text style={styles.portName}>●  雾港疑云</Text><Text style={styles.roomPill}>ROOM 4827</Text><View style={styles.ship}><View style={styles.mast}/><View style={styles.hull}/></View><View style={styles.avatarGroup}><Text>林</Text><Text>M</Text><Text>A</Text><Text>苏</Text><Text>+2</Text></View><Text style={styles.portMeta}>♧  4 / 6 位玩家   |   ◷ 预计 25 分钟</Text></View>
    <Pressable accessibilityLabel="加入语音房间" onPress={onJoin} style={styles.primaryCta}><Text style={styles.ctaText}>♩          加入语音房间                         ›</Text></Pressable>
    <Pressable accessibilityLabel="创建新房间" onPress={onCreate} style={styles.outlineCta} testID="create-room-button"><Text style={styles.outlineText}>⌂          创建新房间                         ›</Text></Pressable>
    <View style={styles.codeCta}><Text style={styles.outlineText}>▦</Text><TextInput accessibilityLabel="房间码" onChangeText={setCode} placeholder="输入房间码" placeholderTextColor="#63756B" style={styles.codeInput} value={code}/><Pressable accessibilityLabel="输入房间码" onPress={onJoin}><Text style={styles.outlineText}>›</Text></Pressable></View>
  </View><BottomTabs /></SafeAreaView>;
}

export function WaitingScreen({ ready, onReady, onStart, onLeave }: { ready: boolean; onReady: () => void; onStart: () => void; onLeave: () => void }) {
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.waiting}><Header back={onLeave} title=""/><Text style={styles.waitTitle}>雾港疑云</Text><Text style={styles.waitingHint}>等待同伴入座</Text><Text style={styles.legacyLabel}>MINT</Text><Text style={styles.codeBadge}>房间 4827    ⇧</Text><View style={styles.banner}><Text style={styles.bannerLight}>♜</Text><Text style={styles.bannerText}>序章将在所有玩家准备后开始</Text></View><Text style={styles.count}>────  玩家 4 / 6  ────</Text><View style={styles.seats}>{players.concat([["", "等待加入", "#DDD7C7"], ["", "等待加入", "#DDD7C7"]]).map(([name, state, tone], index) => <View key={`${name}-${index}`} style={styles.seat}><View style={[styles.seatAvatar, { backgroundColor: tone }]}><Text style={styles.avatarInitial}>{name || "♙"}</Text></View><View><Text style={styles.seatName}>{name || "等待加入"}</Text><Text style={[styles.seatState, index === 0 && ready && styles.ready]}>{index === 0 && ready ? "已准备" : state}</Text></View>{name ? <Text style={styles.mic}>♩</Text> : null}</View>)}</View><View style={styles.micCheck}><Text style={styles.micLarge}>♩</Text><Text>请先确认麦克风可用</Text></View></ScrollView><View style={styles.waitFooter}><Pressable accessibilityLabel="准备好了" onPress={onReady} style={styles.testMic} testID="ready-button"><Text>{ready ? "✓ 已准备" : "♩ 测试麦克风"}</Text></Pressable><Pressable accessibilityLabel="开始房间" disabled={!ready} onPress={onStart} style={[styles.start, !ready && styles.startDisabled]} testID="start-room-button"><Text style={styles.startText}>⌑  开始故事</Text></Pressable></View></SafeAreaView>;
}

function Player({ name, state, speaker, reconnecting }: { name: string; state: string; speaker?: boolean; reconnecting?: boolean }) {
  return <View style={styles.livePlayer}><View style={[styles.liveAvatar, speaker && styles.speakerAvatar, reconnecting && styles.reconnectAvatar]}><Text style={styles.liveInitial}>{name[0]}</Text></View><Text style={styles.liveName}>{name}</Text><Text style={[styles.liveState, speaker && styles.speakingState, reconnecting && styles.reconnectState]}>{reconnecting ? "重新连接中" : state}</Text></View>;
}

export function LiveScreen({ onEnd }: { onEnd: () => void }) {
  const [muted, setMuted] = useState(false); const [speaker, setSpeaker] = useState(true); const [reconnecting, setReconnecting] = useState(false);
  return <SafeAreaView style={styles.liveSafe}><View style={styles.live}><View style={styles.liveTop}><Text style={styles.liveBack}>‹</Text><View><Text style={styles.liveRoom}>雾港疑云</Text><Text style={styles.livePractice}>正在练习</Text><Text style={styles.liveStatus}>▥  语音进行中{"\n"}18:42</Text></View><Text style={styles.liveMore}>⌄</Text></View>
    <View style={styles.players}><Player name="林舟" state="我" /><Player name="Mia" speaker state="正在发言" /><Player name="Alex" state="已静音" /><Player name="苏晴" reconnecting={reconnecting} state="连接中" /></View>
    <View style={styles.clue}><Text style={styles.clueKicker}>⚓   第二幕 · 码头</Text><Text style={styles.clueRule}>────    你的线索    ────</Text><Text style={styles.clueText}>Ask Mia where she was at 10 PM.</Text><Text style={styles.clueHint}>请使用英语完成对话</Text></View>
    <View style={styles.signalRow}>{["林舟 良好", "Mia 良好", "Alex 良好", "苏晴 较弱"].map((signal) => <View key={signal} style={styles.signal}><Text>▥</Text><Text>{signal}</Text></View>)}</View>
    <View style={styles.controls}><Control label={muted ? "打开麦克风" : "静音"} icon="♩" onPress={() => setMuted(!muted)} /><Control label={speaker ? "扬声器开" : "扬声器关"} icon="◖" onPress={() => setSpeaker(!speaker)} /><Control label="触发重连" icon="•••" onPress={() => setReconnecting(!reconnecting)} testID="reconnect-button" /><Control danger label="结束房间" icon="⌕" onPress={onEnd} testID="end-room-button" /></View>
  </View></SafeAreaView>;
}

function Control({ label, icon, danger, onPress, testID }: { label: string; icon: string; danger?: boolean; onPress: () => void; testID?: string }) { return <Pressable accessibilityLabel={label} onPress={onPress} style={styles.control} testID={testID}><View style={[styles.controlCircle, danger && styles.hangup]}><Text style={styles.controlIcon}>{icon}</Text></View><Text style={[styles.controlText, danger && styles.dangerText]}>{label === "触发重连" ? "更多" : label}</Text></Pressable>; }

export function ReportScreen({ error, items, onDone, onRetry }: { error?: string; items: ReportItem[]; onDone: () => void; onRetry: (item: ReportItem) => void }) {
  const reports = items;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.report}><View style={styles.reportHeader}><Text style={styles.back}>‹</Text><View><Text style={styles.reportTitle}>本局英语报告</Text><Text style={styles.legacyReport}>本局口语报告</Text></View><View /></View><Text style={styles.reportSub}>⌁  雾港疑云 · 25 分钟  ⌁</Text><View style={styles.infoCard}><View style={styles.infoImage}/><View><Text style={styles.infoName}>雾港疑云</Text><Text style={styles.infoMeta}>♧ 4 人房间　◷ 25 分钟　▣ 2025/05/18</Text></View></View>
    <View style={styles.scoreCard}><View style={styles.scoreCircle}><Text style={styles.scoreNumber}>{reports[0]?.score ?? "—"}</Text></View><View><Text style={styles.scoreFor}>本局口语评分</Text><Text style={styles.excellent}>表现优秀</Text></View></View>{error ? <Text accessibilityLabel="报告错误">{error}</Text> : null}<Text style={styles.resultTitle}>玩家结果</Text>{reports.map((item, index) => <View key={item.scoreJobId} style={styles.reportRow}><View style={styles.resultAvatar}><Text>{index + 1}</Text></View><Text style={styles.resultName}>{item.playerName}</Text><Text style={styles.resultState}>{item.status}</Text>{item.status === "failed" ? <Pressable accessibilityLabel="重试评分" onPress={() => onRetry(item)}><Text style={styles.retry}>重新提交</Text></Pressable> : <Text style={styles.resultScore}>{item.score ?? "—"}</Text>}</View>)}<Pressable accessibilityLabel="回到大厅" onPress={onDone} style={styles.return}><Text style={styles.returnText}>返回大厅</Text></Pressable></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({
  safe:{backgroundColor:"#FCFAF4",flex:1}, lobby:{flex:1,padding:16}, header:{alignItems:"center",flexDirection:"row",justifyContent:"space-between",paddingTop:6},logo:{alignItems:"center",flexDirection:"row",gap:7},book:{color:"#174B3B",fontSize:24},logoText:{color:"#174638",fontFamily:"serif",fontSize:23,fontWeight:"700"},profile:{alignItems:"center",backgroundColor:"#D4C7B3",borderRadius:19,height:38,justifyContent:"center",width:38},back:{color:"#174638",fontSize:40,lineHeight:40},lobbyTitle:{color:"#194535",fontFamily:"serif",fontSize:27,fontWeight:"700",lineHeight:34,marginTop:18},lobbyPrompt:{color:"#748278",fontSize:11,marginTop:2},smallRule:{alignItems:"center",flexDirection:"row",gap:6,marginVertical:7,width:100},portCard:{backgroundColor:"#173C3D",borderRadius:20,height:270,overflow:"hidden",position:"relative"},portMist:{backgroundColor:"#496365",height:190,opacity:.5,position:"absolute",right:-70,top:70,transform:[{rotate:"-20deg"}],width:390},portName:{color:"#FFF",fontFamily:"serif",fontSize:24,fontWeight:"700",left:18,position:"absolute",top:20},roomPill:{backgroundColor:"#263D3C",borderRadius:10,color:"#FFF",fontSize:12,padding:9,position:"absolute",right:12,top:19},ship:{bottom:76,left:63,position:"absolute"},mast:{backgroundColor:"#1D2E30",height:104,width:3},hull:{backgroundColor:"#172A2B",height:24,marginLeft:-36,width:105},avatarGroup:{bottom:42,flexDirection:"row",left:18,position:"absolute"},portMeta:{bottom:16,color:"#FFF",fontSize:12,left:18,position:"absolute"},primaryCta:{backgroundColor:"#1A563E",borderRadius:12,marginTop:11,padding:13},ctaText:{color:"#FFF",fontSize:16,fontWeight:"800"},outlineCta:{alignItems:"center",borderColor:"#95A498",borderRadius:12,borderWidth:1,flexDirection:"row",justifyContent:"space-between",marginTop:8,padding:12},codeCta:{alignItems:"center",borderColor:"#95A498",borderRadius:12,borderWidth:1,flexDirection:"row",justifyContent:"space-between",marginTop:8,padding:12},outlineText:{color:"#1B513D",fontSize:15,fontWeight:"800"},codeInput:{color:"#174638",flex:1,fontSize:14,marginHorizontal:12},tabs:{borderTopColor:"#E1DED3",borderTopWidth:1,flexDirection:"row",justifyContent:"space-around",paddingBottom:9,paddingTop:7},tab:{color:"#98A298",fontSize:11,textAlign:"center"},tabActive:{color:"#1B573F",fontSize:11,fontWeight:"800",textAlign:"center"},
  waiting:{padding:18,paddingBottom:110},waitTitle:{color:"#194535",fontFamily:"serif",fontSize:35,fontWeight:"700",textAlign:"center"},waitingHint:{color:"#698075",fontSize:12,textAlign:"center"},legacyLabel:{color:"#768B80",fontSize:10,textAlign:"center"},codeBadge:{alignSelf:"center",borderColor:"#CFC4AF",borderRadius:20,borderWidth:1,color:"#4B594F",marginVertical:10,paddingHorizontal:16,paddingVertical:7},banner:{alignItems:"center",backgroundColor:"#123D34",borderRadius:13,flexDirection:"row",height:127,justifyContent:"center",overflow:"hidden"},bannerLight:{color:"#C8B378",fontSize:42,marginRight:20},bannerText:{color:"#FFF2D0",fontFamily:"serif",fontSize:18},count:{color:"#274F40",fontFamily:"serif",fontSize:17,fontWeight:"700",marginVertical:20,textAlign:"center"},seats:{flexDirection:"row",flexWrap:"wrap",gap:12},seat:{alignItems:"center",borderColor:"#D8CFBC",borderRadius:14,borderWidth:1,flexDirection:"row",gap:10,height:132,padding:12,width:"48%"},seatAvatar:{alignItems:"center",borderRadius:34,height:64,justifyContent:"center",width:64},avatarInitial:{color:"#FFF",fontSize:20},seatName:{color:"#204A3B",fontFamily:"serif",fontSize:18,fontWeight:"700"},seatState:{color:"#5E7569",fontSize:12,marginTop:7},ready:{backgroundColor:"#2E7156",borderRadius:12,color:"#FFF",overflow:"hidden",paddingHorizontal:8,paddingVertical:4},mic:{color:"#1C6048",fontSize:18,position:"absolute",right:10},micCheck:{alignItems:"center",backgroundColor:"#F8F3E8",borderColor:"#E9DFCC",borderRadius:12,borderWidth:1,flexDirection:"row",gap:12,marginTop:24,padding:18},micLarge:{color:"#215943",fontSize:28},waitFooter:{backgroundColor:"#FCFAF4",borderTopColor:"#EEE6D5",borderTopWidth:1,bottom:0,flexDirection:"row",gap:12,left:0,padding:14,position:"absolute",right:0},testMic:{alignItems:"center",borderColor:"#1E503D",borderRadius:12,borderWidth:1,flex:1,padding:17},start:{alignItems:"center",backgroundColor:"#1C563E",borderRadius:12,flex:1,padding:17},startDisabled:{backgroundColor:"#9EAEA4"},startText:{color:"#FFF",fontSize:16,fontWeight:"800"},
  liveSafe:{backgroundColor:"#061E1D",flex:1},live:{backgroundColor:"#082524",flex:1,padding:18},liveTop:{alignItems:"center",flexDirection:"row",justifyContent:"space-between",marginTop:6},liveBack:{borderColor:"#90A7A0",borderRadius:24,borderWidth:1,color:"#FFF",fontSize:31,height:42,textAlign:"center",width:42},liveMore:{borderColor:"#90A7A0",borderRadius:24,borderWidth:1,color:"#FFF",fontSize:31,height:42,textAlign:"center",width:42},liveRoom:{color:"#FFF6DA",fontFamily:"serif",fontSize:19,textAlign:"center"},livePractice:{color:"#DAE8DD",fontSize:10,textAlign:"center"},liveStatus:{color:"#78E2AE",fontSize:13,lineHeight:20,textAlign:"center"},players:{flexDirection:"row",flexWrap:"wrap",justifyContent:"space-between",marginTop:36},livePlayer:{alignItems:"center",height:164,width:"47%"},liveAvatar:{alignItems:"center",backgroundColor:"#284441",borderColor:"#CFE7DC",borderRadius:55,borderWidth:2,height:102,justifyContent:"center",width:102},speakerAvatar:{borderColor:"#75F6BD",borderWidth:5},reconnectAvatar:{borderColor:"#D9A93F"},liveInitial:{color:"#FFF",fontSize:32},liveName:{color:"#FFF9E8",fontFamily:"serif",fontSize:18,marginTop:5},liveState:{color:"#A9B8B2",fontSize:12},speakingState:{backgroundColor:"#3E9470",borderRadius:12,color:"#FFF",paddingHorizontal:8,paddingVertical:3},reconnectState:{color:"#E8B44B"},clue:{borderColor:"#9A8150",borderWidth:1,marginTop:4,padding:17},clueKicker:{color:"#D6B971",fontFamily:"serif",fontSize:17},clueRule:{color:"#6DD6A1",fontSize:12,marginTop:14,textAlign:"center"},clueText:{color:"#FFF1D2",fontFamily:"serif",fontSize:20,marginTop:14,textAlign:"center"},clueHint:{color:"#B6C5B8",fontSize:13,marginTop:18,textAlign:"center"},signalRow:{flexDirection:"row",gap:7,marginTop:14},signal:{alignItems:"center",backgroundColor:"#173532",borderColor:"#405D55",borderRadius:7,borderWidth:1,flex:1,padding:7},controls:{backgroundColor:"#142D2B",borderRadius:28,flexDirection:"row",justifyContent:"space-around",marginTop:26,paddingVertical:16},control:{alignItems:"center",width:70},controlCircle:{alignItems:"center",backgroundColor:"#24413D",borderRadius:31,height:62,justifyContent:"center",width:62},hangup:{backgroundColor:"#C84A45"},controlIcon:{color:"#FFF",fontSize:22},controlText:{color:"#E8E4D8",fontSize:11,marginTop:6,textAlign:"center"},dangerText:{color:"#F18A7C"},
  report:{padding:18,paddingBottom:28},reportHeader:{alignItems:"center",flexDirection:"row",justifyContent:"space-between"},reportTitle:{color:"#1B4B3C",fontSize:20,fontWeight:"800"},legacyReport:{color:"#65796D",fontSize:10,textAlign:"center"},reportSub:{color:"#778078",marginVertical:10,textAlign:"center"},infoCard:{alignItems:"center",borderColor:"#DBDDD4",borderRadius:15,borderWidth:1,flexDirection:"row",gap:13,padding:10},infoImage:{backgroundColor:"#244D49",borderRadius:9,height:58,width:64},infoName:{color:"#1B4A3B",fontFamily:"serif",fontSize:18,fontWeight:"700"},infoMeta:{color:"#788078",fontSize:11,marginTop:8},scoreCard:{alignItems:"center",backgroundColor:"#FFFEFA",borderColor:"#EFF0E8",borderRadius:16,borderWidth:1,flexDirection:"row",gap:18,marginTop:16,padding:18},scoreCircle:{alignItems:"center",borderColor:"#36966C",borderRadius:62,borderWidth:8,height:124,justifyContent:"center",width:124},scoreNumber:{color:"#1F654B",fontFamily:"serif",fontSize:54},scoreFor:{color:"#1B4638",fontSize:15,fontWeight:"700"},excellent:{color:"#299368",fontFamily:"serif",fontSize:28,marginTop:7},scoreDetails:{color:"#50665A",fontSize:11,marginTop:12},metrics:{backgroundColor:"#FFF",borderColor:"#E7E8DF",borderRadius:15,borderWidth:1,flexDirection:"row",justifyContent:"space-around",marginTop:16,paddingVertical:14},metric:{alignItems:"center",width:"24%"},metricScore:{color:"#176144",fontFamily:"serif",fontSize:24},metricBar:{backgroundColor:"#3DA275",borderRadius:5,height:6,marginTop:7,width:"70%"},tip:{alignItems:"center",backgroundColor:"#F5F9F0",borderColor:"#E2EAD9",borderRadius:13,borderWidth:1,flexDirection:"row",gap:15,marginTop:14,padding:16},tipIcon:{color:"#5AA178",fontSize:32},tipTitle:{color:"#24523E",fontSize:15,fontWeight:"800"},resultTitle:{color:"#28523F",fontSize:16,fontWeight:"800",marginTop:18},reportRow:{alignItems:"center",backgroundColor:"#FFF",borderColor:"#E8E8DF",borderRadius:14,borderWidth:1,flexDirection:"row",gap:10,marginTop:10,padding:11},resultAvatar:{alignItems:"center",backgroundColor:"#305D4B",borderRadius:20,height:40,justifyContent:"center",width:40},resultName:{color:"#1C4335",fontFamily:"serif",fontSize:17,fontWeight:"700",width:50},resultState:{color:"#417D60",flex:1,fontSize:12},failed:{color:"#DA5B3D"},resultScore:{color:"#1D7654",fontFamily:"serif",fontSize:24},retry:{color:"#B85036",fontSize:11},return:{alignItems:"center",backgroundColor:"#195F45",borderRadius:10,marginTop:14,padding:17},returnText:{color:"#FFF",fontSize:18,fontWeight:"800"},
});
